# This is a basic workflow to help you get started with Actions

name: Cypress Tests

# Controls when the workflow will run
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/trello.cy.js
          browser: edge
